// Code generated by lisette from src/; DO NOT EDIT.

package httpserver

import (
	"context"
	"encoding/json"
	lisette "github.com/ivov/lisette/prelude"
	"log/slog"
	"net/http"
	"sync/atomic"
)

const CONTENT_TYPE string = "Content-Type"

const CONTENT_TYPE_PLAIN string = "text/plain; charset=utf-8"

const CONTENT_TYPE_JSON string = "application/json"

type CheckFunc func(context.Context) error

type NamedCheck struct {
	name  string
	check CheckFunc
}

func liveness_handler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	w.Header().Set(CONTENT_TYPE, CONTENT_TYPE_PLAIN)
	w.WriteHeader(http.StatusOK)
	w.Write([]uint8("ok"))
}

func readiness_handler(ready *atomic.Bool, checks []NamedCheck, logger *slog.Logger) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		if !ready.Load() {
			w.Header().Set(CONTENT_TYPE, CONTENT_TYPE_PLAIN)
			w.WriteHeader(http.StatusServiceUnavailable)
			w.Write([]uint8("shutting down"))
			return
		}
		for _, c := range checks {
			callee_2 := c.check
			ret_3 := callee_2(r.Context())
			var result_4 lisette.Result[struct{}, error]
			if ret_3 != nil {
				result_4 = lisette.MakeResultErr[struct{}, error](ret_3)
			} else {
				result_4 = lisette.MakeResultOk[struct{}, error](struct{}{})
			}
			subject_1 := result_4
			if subject_1.Tag == lisette.ResultErr {
				e := subject_1.ErrVal
				logger.WarnContext(r.Context(), "readiness check failed", "check", c.name, "error", e.Error())
				w.Header().Set(CONTENT_TYPE, CONTENT_TYPE_JSON)
				w.WriteHeader(http.StatusServiceUnavailable)
				body := make(map[string]string)
				body["failed_check"] = c.name
				body["error"] = e.Error()
				json.NewEncoder(w).Encode(body)
				return
			}
		}
		w.Header().Set(CONTENT_TYPE, CONTENT_TYPE_PLAIN)
		w.WriteHeader(http.StatusOK)
		w.Write([]uint8("ok"))
	})
}
