# Module path other Go projects import this library as. Keep in sync with go.mod.
GO_MODULE := github.com/banan-tech/httpserver
# Directory `lis build` writes the generated `httpserver` Go package into.
GEN_PKG   := target/httpserver

.PHONY: emit
emit: ## Compile Lisette -> Go and emit the library package into the repo root
	lis build
	@# Root is generated-only: drop the previously emitted (and pre-Lisette) .go.
	@find . -maxdepth 1 -name '*.go' -delete
	@# Copy each generated file out, stamping the standard "do not edit" header.
	@for f in $(GEN_PKG)/*.go; do \
		out="$$(basename "$$f")"; \
		{ printf '// Code generated by lisette from src/; DO NOT EDIT.\n\n'; cat "$$f"; } > "$$out"; \
		echo "  emit $$out"; \
	done
	@gofmt -w *.go
	@# Reconcile go.mod: keep the module path, adopt the toolchain's go version
	@# and pin the Lisette prelude at the exact version `lis build` resolved.
	@test -f go.mod || go mod init $(GO_MODULE)
	@PRELUDE="$$(awk '/ivov\/lisette\/prelude/ {print $$2"@"$$3}' $(GEN_PKG)/../go.mod)"; \
	 GOVER="$$(awk '/^go [0-9]/ {print $$2; exit}' $(GEN_PKG)/../go.mod)"; \
	 go mod edit -go="$$GOVER" -require="$$PRELUDE"
	go mod tidy
	go build .
	@echo "emitted $(GO_MODULE) -> repo root"

.PHONY: clean-emit
clean-emit: ## Remove the emitted Go files from the repo root
	@find . -maxdepth 1 -name '*.go' -delete
	@echo "removed emitted .go from repo root"
