// Code generated by lisette from src/; DO NOT EDIT.

package httpserver

import (
	"fmt"
	lisette "github.com/ivov/lisette/prelude"
	"log/slog"
	"net/http"
	"os"
	"time"
)

type Config struct {
	addr                   string
	handler                lisette.Option[http.Handler]
	metrics_handler        lisette.Option[http.Handler]
	logger                 *slog.Logger
	read_header_timeout    time.Duration
	read_timeout           time.Duration
	write_timeout          time.Duration
	idle_timeout           time.Duration
	shutdown_timeout       time.Duration
	readiness_checks       []NamedCheck
	shutdown_hooks         []ShutdownHook
	disable_default_probes bool
	liveness_path          string
	readiness_path         string
}

func default_config() Config {
	return Config{
		addr:                   ":8080",
		logger:                 DefaultLogger(),
		read_header_timeout:    5 * time.Second,
		read_timeout:           15 * time.Second,
		write_timeout:          70 * time.Second,
		idle_timeout:           90 * time.Second,
		shutdown_timeout:       15 * time.Second,
		liveness_path:          "/livez",
		readiness_path:         "/readyz",
		handler:                lisette.MakeOptionNone[http.Handler](),
		metrics_handler:        lisette.MakeOptionNone[http.Handler](),
		disable_default_probes: false,
	}
}

func DefaultLogger() *slog.Logger {
	_arg_3 := os.Stdout
	opt_1 := lisette.MakeOptionSome[slog.Leveler](slog.LevelInfo)
	var unwrap_2 slog.Leveler
	if opt_1.Tag == lisette.OptionSome {
		unwrap_2 = opt_1.SomeVal
	}
	return slog.New(slog.NewJSONHandler(_arg_3, &slog.HandlerOptions{Level: unwrap_2}))
}

type ServerOption func(*Config)

func WithAddr(addr string) ServerOption {
	return func(c *Config) {
		c.addr = addr
	}
}

func WithHandler(h http.Handler) ServerOption {
	return func(c *Config) {
		c.handler = lisette.MakeOptionSome[http.Handler](h)
	}
}

func WithMetricsHandler(h http.Handler) ServerOption {
	return func(c *Config) {
		c.metrics_handler = lisette.MakeOptionSome[http.Handler](h)
	}
}

func WithLogger(logger *slog.Logger) ServerOption {
	return func(c *Config) {
		c.logger = logger
	}
}

func WithReadHeaderTimeout(d time.Duration) ServerOption {
	return func(c *Config) {
		c.read_header_timeout = d
	}
}

func WithReadTimeout(d time.Duration) ServerOption {
	return func(c *Config) {
		c.read_timeout = d
	}
}

func WithWriteTimeout(d time.Duration) ServerOption {
	return func(c *Config) {
		c.write_timeout = d
	}
}

func WithIdleTimeout(d time.Duration) ServerOption {
	return func(c *Config) {
		c.idle_timeout = d
	}
}

func WithShutdownTimeout(d time.Duration) ServerOption {
	return func(c *Config) {
		c.shutdown_timeout = d
	}
}

func WithReadinessCheck(name string, check CheckFunc) ServerOption {
	return func(c *Config) {
		ref_1 := c
		ref_1.readiness_checks = append(c.readiness_checks, NamedCheck{
			name:  name,
			check: check,
		})
	}
}

func WithShutdownHook(hook ShutdownHook) ServerOption {
	return func(c *Config) {
		ref_1 := c
		ref_1.shutdown_hooks = append(c.shutdown_hooks, hook)
	}
}

func WithPortFromEnv() ServerOption {
	return func(c *Config) {
		port := os.Getenv("PORT")
		if port != "" {
			c.addr = fmt.Sprintf(":%s", port)
		}
	}
}

func WithoutDefaultProbes() ServerOption {
	return func(c *Config) {
		c.disable_default_probes = true
	}
}

func WithLivenessPath(path string) ServerOption {
	return func(c *Config) {
		c.liveness_path = path
	}
}

func WithReadinessPath(path string) ServerOption {
	return func(c *Config) {
		c.readiness_path = path
	}
}
